# Generated by Django 4.1.2 on 2022-10-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_host_room_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Typ',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='typprace',
        ),
    ]
