# Generated by Django 4.1.2 on 2022-10-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_topic_typ_rename_topic_room_typprace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodinyd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hodinym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='hodinyden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.hodinyd'),
        ),
        migrations.AddField(
            model_name='room',
            name='hodinymesic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.hodinym'),
        ),
        migrations.AddField(
            model_name='room',
            name='plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.plat'),
        ),
    ]
