# Generated by Django 4.1.2 on 2022-10-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_hodinyd_hodinym_plat_room_hodinyden_room_hodinymesic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Platm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='plat',
        ),
        migrations.AlterField(
            model_name='hodinyd',
            name='name',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='hodinym',
            name='name',
            field=models.FloatField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Plat',
        ),
        migrations.AddField(
            model_name='room',
            name='plathodinovy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.plath'),
        ),
        migrations.AddField(
            model_name='room',
            name='platmesicni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.platm'),
        ),
    ]
