# Generated by Django 4.1.2 on 2022-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_plath_platm_remove_room_plat_alter_hodinyd_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plath',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='platm',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
