# Generated by Django 4.1.2 on 2022-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_hodinyd_name_alter_hodinym_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='Zadávající',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='description',
            new_name='popis_práce',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hodinyden',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hodinymesic',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='plathodinovy',
        ),
        migrations.RemoveField(
            model_name='room',
            name='platmesicni',
        ),
        migrations.RemoveField(
            model_name='room',
            name='typprace',
        ),
        migrations.AddField(
            model_name='room',
            name='Hodinový_plat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='Hodiny_za_den',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='Hodiny_za_měsíc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='Měsíční_mzda',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='Název_pozice',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='typ_práce',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
