# Generated by Django 4.1.2 on 2022-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_host_room_zadávající_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Název_pozice',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='typ_práce',
            field=models.CharField(max_length=30),
        ),
    ]
