# Generated by Django 4.1.2 on 2022-10-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_room_název_pozice_alter_room_typ_práce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Název_pozice',
            new_name='Nazev_pozice',
        ),
    ]
