# Generated by Django 4.1.2 on 2022-10-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_název_pozice_room_nazev_pozice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
