# Generated by Django 4.1.2 on 2022-11-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_room_typ_práce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='typ_práce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.typprace'),
        ),
    ]
