# Generated by Django 4.1.2 on 2022-11-14 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_alter_room_typ_práce'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dotazující',
            field=models.ManyToManyField(blank=True, related_name='Účastníci', to=settings.AUTH_USER_MODEL),
        ),
    ]
