# Generated by Django 4.1.2 on 2022-11-14 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0020_room_dotazující'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dotazující',
            field=models.ManyToManyField(blank=True, related_name='dotazující', to=settings.AUTH_USER_MODEL),
        ),
    ]
